--Para buscar a idade do cliente, normalmente utilizamos a seguinte expressão:

CAST(GETDATE() - C.DT_NASCIMENTO AS FLOAT) /365.25

--Mas, neste caso, é necessário informar a data da compra do pedido e não a atual:
--CAST(P.DATA_EMISSAO - C.DT_NASCIMENTO AS FLOAT)/365.25

--A consulta para extrair essa informação está demonstrada adiante:
 
-- Adicionando o campo DT_NASCIMENTO na tabela de clientes
ALTER TABLE TB_CLIENTE ADD  DT_NASCIMENTO DATETIME

-- Incluindo datas aleatórias para o Nascimento

DECLARE @CODCLI INT

DECLARE CR_Cliente CURSOR KEYSET 
FOR SELECT CODCLI FROM TB_CLIENTE

OPEN CR_CLIENTE

FETCH FIRST FROM CR_CLIENTE INTO @CODCLI

WHILE @@FETCH_STATUS =0
	BEGIN

	UPDATE TB_CLIENTE SET DT_NASCIMENTO = CAST('1960.1.1' AS DATETIME)  + RAND() * 18250
	WHERE CODCLI = @CODCLI

	FETCH NEXT FROM CR_CLIENTE INTO @CODCLI

	END

CLOSE CR_CLIENTE
DEALLOCATE CR_CLIENTE

--Consultando a tabela
SELECT * from TB_CLIENTE

-- Consultando com a coluna de Faixa Etária
SELECT 	
YEAR(P.DATA_EMISSAO) AS ANO, 
MONTH(P.DATA_EMISSAO) AS MES , 
SUM(P.VLR_TOTAL) AS TOTAL,
CASE 
	WHEN CAST(P.DATA_EMISSAO - C.DT_NASCIMENTO AS FLOAT)/365.25  <= 30 THEN 1
	WHEN CAST(P.DATA_EMISSAO - C.DT_NASCIMENTO AS FLOAT)/365.25  <= 40 THEN 2
	ELSE 3 
END AS Faixa_Etaria
FROM 	TB_PEDIDO AS P
JOIN 	tb_CLIENTE AS C ON P.CODCLI = C.CODCLI
WHERE 	YEAR(P.DATA_EMISSAO) = 2014
GROUP BY YEAR(P.DATA_EMISSAO), MONTH(P.DATA_EMISSAO)  , 
	CASE 
	WHEN CAST(P.DATA_EMISSAO - C.DT_NASCIMENTO AS FLOAT)/365.25  <= 30 THEN 1
	WHEN CAST(P.DATA_EMISSAO - C.DT_NASCIMENTO AS FLOAT)/365.25  <= 40 THEN 2
	ELSE 3 END
	 


