CREATE DATABASE DW_SSIS
GO

USE DW_SSIS
GO

CREATE TABLE DIM_REGIAO (
ID_REGIAO		INT 	IDENTITY PRIMARY KEY,
SIGLA			CHAR(2),
ESTADO			VARCHAR(20),
CIDADE			VARCHAR(40) )

GO

CREATE TABLE DIM_PERIODO (
ID_PERIODO	INT 	IDENTITY PRIMARY KEY ,
ANO		INT,
MES		INT,
DIA		INT)

GO

CREATE TABLE DIM_PRODUTO (
ID_PRODUTO	INT 	IDENTITY PRIMARY KEY,
PRODUTO	VARCHAR(40),
TIPO		VARCHAR(40),
UNIDADE	VARCHAR(40) )

GO
CREATE TABLE FATO_VENDA (
ID			INT		IDENTITY	PRIMARY KEY,
ID_PERIODO	INT	,
ID_REGIAO	INT,
ID_PRODUTO	INT,
QUANTIDADE	INT,
PEDIDOS	INT,
VALOR		DECIMAL(10,2))


GO
ALTER TABLE FATO_VENDA ADD 
CONSTRAINT FK_FATO_VENDA_PERIODO FOREIGN KEY (ID_PERIODO) REFERENCES DIM_PERIODO (ID_PERIODO),
CONSTRAINT FK_FATO_VENDA_REGIAO  FOREIGN KEY (ID_REGIAO) REFERENCES DIM_REGIAO(ID_REGIAO) ,
CONSTRAINT FK_FATO_VENDA_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES DIM_PRODUTO(ID_PRODUTO)


GO

CREATE TABLE TBPEDIDOS (
NUM_PEDIDO		INT,
CODCLI			INT,
CODVEN			SMALLINT,
DATA_EMISSAO	DATETIME,
VLR_TOTAL		NUMERIC(18, 2),
SITUACAO		VARCHAR(1) )

GO


CREATE TABLE TB_CLIENTES (
	CODCLI		INT PRIMARY KEY,
	NOME		VARCHAR(50) ,
	FANTASIA	VARCHAR(20) ,
	ENDERECO	VARCHAR(200),
	CEP			VARCHAR(8) ,
	CNPJ		VARCHAR(18),
	INSCRICAO	VARCHAR(19),
	FONE1		VARCHAR(15),
	FAX			VARCHAR(15),
	E_MAIL		VARCHAR(35),
	DATA_CAD	DATETIME,
	ICMS		FLOAT)

	