SELECT TOTAL,META,
	CASE 
	WHEN TOTAL/META < .5 THEN -1
	WHEN TOTAL/META < .7 THEN 0
	ELSE 1
	END AS STATUS	
FROM 
	(SELECT 
	SUM(VLR_TOTAL) AS TOTAL,
	300000 AS META
	FROM PEDIDOS.DBO.TB_PEDIDO
	WHERE YEAR(DATA_EMISSAO)=2014
	AND MONTH(DATA_EMISSAO) = 09
	) AS A


	SELECT 
	SUM(VLR_TOTAL) AS TOTAL,
	MONTH(VLR_TOTAL) AS MES
	FROM PEDIDOS.DBO.TB_PEDIDO
	WHERE YEAR(DATA_EMISSAO)=2014
	AND MONTH(VLR_TOTAL) IS NOT NULL
	GROUP BY MONTH(VLR_TOTAL)
	ORDER BY MES


